[18.0][ADD] calendar_public_holiday
OCA/calendar pull request #142
Opened 2024-12-26 11:48 UTC by xaviedoanhduy

### context:

- from this comment https://github.com/OCA/hr-holidays/pull/110#issuecomment-2096096367, extract some features from `hr_holidays_public` module into new module so that it can be used in other contexts and no longer depends on HR.

### note:

- rename the `hr.holidays.public` model and related models to `calendar.public.holiday` to match the Calendar repo.
- fix words like Holidays Public to Public holidays (because it is misspelled)
- moving tests and modifications from the old module will only concern the scope of functions in this module.

2025-01-08 15:46 UTC, victoralmau approved these changes
Code and functional review.

IMO the copyright of the corresponding files must be maintained to respect the attribution of all because this module is a “split” of the already existing `hr_holidays_public` module.

2025-01-10 02:40 UTC, xaviedoanhduy commented
> Code and functional review.
> 
> IMO the copyright of the corresponding files must be maintained to respect the attribution of all because this module is a “split” of the already existing `hr_holidays_public` module.

thanks for your suggestion, I have updated the copyright.

2025-01-10 07:11 UTC, victoralmau approved these changes
Ping @chienandalu

2025-01-10 07:38 UTC, pedrobaeza commented
Isn't the migration scripts missing here?

2025-01-10 08:56 UTC, chienandalu commented
> Isn't the migration scripts missing here?

I'd say that the hr_holidays_public stuff relative to time-off is goint to be still needed so the migration work could be done there, isn't it?

2025-01-10 08:58 UTC, pedrobaeza commented
I think it should be done here, as the opinion holidays should be transferred here.

2025-01-13 03:52 UTC, xaviedoanhduy commented
DRAFT: ADDING MIGRATION SCRIPT DATA

2025-02-05 11:02 UTC, victoralmau commented on calendar_public_holiday/__manifest__.py
> +    "external_dependencies": {"python": ["openupgradelib"]},
```suggestion
    "external_dependencies": {"python": ["openupgradelib"]},
```

I am not sure if this dependency should be added, what do you think @pedrobaeza  ?

2025-02-05 11:27 UTC, pedrobaeza commented on calendar_public_holiday/__manifest__.py
> +    "external_dependencies": {"python": ["openupgradelib"]},
No, it shouldn't be needed, unless it's used in business logic.

2025-02-11 08:17 UTC, victoralmau commented
Ping @pedrobaeza can you review it?

2025-02-12 07:46 UTC, pedrobaeza requested changes
Thanks for the efforts. Apart from the inside comments, other points:

- A plain user shouldn't be able to create nor modify public holidays as it's happening right now (try with demo user in runboat).
- I think the menus should be inside Calendar > Configuration.

2025-02-12 07:46 UTC, pedrobaeza commented on calendar_public_holiday/data/data.xml
> +        <field name="name">Holidays</field>
I think we should take the occasion to rename it:

```suggestion
        <field name="name">Public Holidays</field>
```

2025-02-12 07:46 UTC, pedrobaeza commented on calendar_public_holiday/__manifest__.py
> +    "author": "Camptocamp," "Odoo Community Association (OCA)",
I think this module should have the same authors as the original `hr_holidays_public` one (apart from yours).

2025-02-12 07:46 UTC, pedrobaeza commented on calendar_public_holiday/hooks.py
> +# Copyright 2024 Camptocamp
Sorry for not noticing in my previous comment. As this is used in a hook, not on a migration script (that's what I meant for "business logic"), you should add the external dependency.

2025-02-12 07:46 UTC, pedrobaeza commented on calendar_public_holiday/models/calendar_public_holiday.py
> +    _rec_name = "year"
We should put first the most modern one.

```suggestion
    _rec_name = "year desc"
```

2025-02-12 07:46 UTC, pedrobaeza commented on calendar_public_holiday/models/calendar_public_holiday.py
> +        "Calendar Year", required=True, default=fields.Date.today().year
If not, I think this is going to be a static value.

```suggestion
        "Calendar Year", required=True, default=lambda self: fields.Date.today().year
```

2025-02-12 08:28 UTC, xaviedoanhduy commented
> A plain user shouldn't be able to create nor modify public holidays as it's happening right now (try with demo user in runboat).

Hi @pedrobaeza, since this module no longer depends on `hr_holidays` but instead on the `calendar` module, I changed the access of the models to be the same as in the dependent module (calendar) with the permission groups, see: https://github.com/odoo/odoo/blob/4209d441afa058a87e142b44d6e33a546741dd2b/addons/calendar/security/ir.model.access.csv?plain=1#L7-L8

2025-02-12 08:33 UTC, pedrobaeza commented
Yes, but they shouldn't follow the same rules, as public holidays are defined by managers, not by plain users. When adding `hr_holidays_public`, you can extend the permissions to allow HR managers to set them, but on this base module, only settings users should be able to modify this important information.

2025-02-12 08:43 UTC, xaviedoanhduy commented
> Yes, but they shouldn't follow the same rules, as public holidays are defined by managers, not by plain users. When adding `hr_holidays_public`, you can extend the permissions to allow HR managers to set them, but on this base module, only settings users should be able to modify this important information.

Thanks for clarifying. I have updated the permission group on the models of this module.

2025-02-13 07:07 UTC, victoralmau approved these changes

2025-02-13 07:15 UTC, pedrobaeza commented
Don't remove the super-menu "Public Holidays". Just host it inside the "Configuration" one. Please keep also the empty lines out.

2025-02-13 11:17 UTC, pedrobaeza approved these changes
Thank you!

/ocabot merge nobump

2025-02-13 11:20 UTC, merged